-- ============================================
-- 04 Customer Value Analysis
-- ============================================

-- Question:
-- Which types of customers are the most valuable?

-- Description:
-- This query segments customers by:
-- - Customer segment (e.g. VIP, Premium, etc.)
-- - App usage
-- - Email opt-in status
--
-- It calculates:
-- 1. Number of customers
-- 2. Total lifetime value (LTV)
--
-- This helps identify which combinations of behaviours
-- are associated with higher customer value.

-- Data Source:
-- Original dataset: Kaggle (E-commerce Customer Behaviour Dataset)
-- Query environment: Google BigQuery (katiasprojects.ecom_customer_behavior.customers)

SELECT
  segment,
  has_app,
  email_opt_in,

  -- Number of unique customers
  COUNT(DISTINCT customer_id) AS customer_count,

  -- Total lifetime value generated by this group
  SUM(lifetime_value) AS total_lifetime_value,

  -- Average lifetime value per customer (useful for comparison)
  ROUND(AVG(lifetime_value), 2) AS avg_lifetime_value

FROM `katiasprojects.ecom_customer_behavior.customers`

GROUP BY segment, has_app, email_opt_in

ORDER BY total_lifetime_value DESC;

-- ============================================
-- Insight:
-- Customers who both use the app and opt into email
-- consistently generate the highest total and average
-- lifetime value across segments. This highlights
-- multi-channel engagement as a key driver of long-term revenue.
-- ============================================
